### ISSUE TITLE
Update version in dependent repositories

### ISSUE THREAD

**Issue by thschue** [git-releaser/git-releaser#15]
When releasing a new version, a pull request in other repositories that contain this app should be created.

These things may be defined as follows:

```
additionalRelease:
  - repo: <repourl>
    paths: 
    - path1
    - path2
```

The line in which the version should be updated will be annotated with <x-release-config:name>

When found, a PR for updating this will be raised
